apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tf-atom-iam-openid-connect-provider-aws
  description: "Terraform atom: AWS IAM OpenID Connect Provider - creates an OIDC identity provider for keyless auth"
  annotations:
    github.com/project-slug: PlatformStackPulse/tf-atom-iam-openid-connect-provider-aws
    backstage.io/techdocs-ref: dir:.
  tags: [terraform, aws, atom, iam]
  links:
    - url: https://github.com/PlatformStackPulse/tf-atom-iam-openid-connect-provider-aws
      title: GitHub Repository
      icon: github
spec:
  type: terraform-module
  lifecycle: production
  owner: platform-team
  system: terraform-atoms
